//
// Created by 1 on 27.04.2017.
//

#ifndef ALGORITHMS_AND_DATA_STRUCTURES_PERSISTENT_STACK_H
#define ALGORITHMS_AND_DATA_STRUCTURES_PERSISTENT_STACK_H

#endif //ALGORITHMS_AND_DATA_STRUCTURES_PERSISTENT_STACK_H
